setwd("./Desktop/cleandata/")
library(tidyverse)
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(url, method = "curl", destfile = "activity.zip")
unzip("activity.zip")
labels <- read.table("./UCI HAR Dataset/activity_labels.txt",col.names = c("activityCode","activityName"))
features <- read.table("./UCI HAR Dataset/features.txt",col.names = c("featureNumber","featureName"))
trainSubjects <- read.table("./UCI HAR Dataset/train/subject_train.txt", col.names = c("subject"))
trainData <- read.table("./UCI HAR Dataset/train/X_train.txt", col.names = features$featureName)
trainActivity <- read.table("./UCI HAR Dataset/train/y_train.txt", col.names = c("activityCode"))
testSubjects <- read.table("./UCI HAR Dataset/test/subject_test.txt", col.names = c("subject"))
testData <- read.table("./UCI HAR Dataset/test/X_test.txt", col.names = features$featureName)
testActivity <- read.table("./UCI HAR Dataset/test/y_test.txt", col.names = c("activityCode"))
trainData <- cbind(trainActivity,trainSubjects,trainData)
testData <- cbind(testActivity,testSubjects,testData)
combData <- rbind(trainData,testData)
combData <- merge(labels,combData,by = "activityCode", all = TRUE)
